In [1]:
from tensorflow.keras.layers import Input, Lambda, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator,load_img
from tensorflow.keras.models import Sequential
import numpy as np
from glob import glob
import matplotlib.pyplot as plt
from keras.applications import InceptionV3

In [2]:
IMAGE_SIZE = [224,224]
train_path = '/content/drive/MyDrive/card dataset/dataset/train'
valid_path = '/content/drive/MyDrive/card dataset/dataset/valid'

In [3]:
inc = InceptionV3(input_shape=IMAGE_SIZE + [3], weights='imagenet', include_top=False)

87910968/87910968 [==============================] - 0s 0us/step


In [4]:
for layer in inc.layers:
    layer.trainable = False

In [5]:
folders = glob("/content/drive/MyDrive/card dataset/dataset/train/*")
folders

['/content/drive/MyDrive/card dataset/dataset/train/ten of spades',
 '/content/drive/MyDrive/card dataset/dataset/train/two of spades',
 '/content/drive/MyDrive/card dataset/dataset/train/two of diamonds',
 '/content/drive/MyDrive/card dataset/dataset/train/three of spades',
 '/content/drive/MyDrive/card dataset/dataset/train/two of clubs',
 '/content/drive/MyDrive/card dataset/dataset/train/three of clubs',
 '/content/drive/MyDrive/card dataset/dataset/train/three of diamonds',
 '/content/drive/MyDrive/card dataset/dataset/train/three of hearts',
 '/content/drive/MyDrive/card dataset/dataset/train/two of hearts',
 '/content/drive/MyDrive/card dataset/dataset/train/ten of hearts',
 '/content/drive/MyDrive/card dataset/dataset/train/ten of diamonds',
 '/content/drive/MyDrive/card dataset/dataset/train/six of spades',
 '/content/drive/MyDrive/card dataset/dataset/train/seven of hearts',
 '/content/drive/MyDrive/card dataset/dataset/train/six of hearts',
 '/content/drive/MyDrive/card data

In [6]:
len(folders)

53

In [7]:
x = Flatten()(inc.output)

In [8]:
prediction = Dense(len(folders), activation='softmax')(x)
model = Model(inputs=inc.input, outputs=prediction)

In [9]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv2d (Conv2D)                (None, 111, 111, 32  864         ['input_1[0][0]']                
                                )                                                                 
                                                                                                  
 batch_normalization (BatchNorm  (None, 111, 111, 32  96         ['conv2d[0][0]']                 
 alization)                     )                                                             

In [10]:
model.compile(
  loss='categorical_crossentropy',
  optimizer='adam',
  metrics=['accuracy']
)

In [11]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)

In [12]:
training_set = train_datagen.flow_from_directory('/content/drive/MyDrive/card dataset/dataset/train',
                                                 target_size = (224, 224),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

Found 7624 images belonging to 53 classes.


In [13]:
test_set = test_datagen.flow_from_directory('/content/drive/MyDrive/card dataset/dataset/valid',
                                            target_size = (224, 224),
                                            batch_size = 32,
                                            class_mode = 'categorical')

Found 265 images belonging to 53 classes.


In [ ]:
cnn_model = model.fit_generator(
  training_set,
  validation_data=test_set,
  epochs=25,
  steps_per_epoch=len(training_set),
  validation_steps=len(test_set)
)

<ipython-input-24-0ef64056e0be>:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  cnn_model = model.fit_generator(


Epoch 1/25
239/239 [==============================] - 113s 461ms/step - loss: 3.8033 - accuracy: 0.7792 - val_loss: 11.4945 - val_accuracy: 0.5660
Epoch 2/25
239/239 [==============================] - 109s 455ms/step - loss: 3.7559 - accuracy: 0.7878 - val_loss: 11.6718 - val_accuracy: 0.5660
Epoch 3/25
239/239 [==============================] - 107s 447ms/step - loss: 3.2800 - accuracy: 0.8111 - val_loss: 13.5517 - val_accuracy: 0.5736
Epoch 4/25
239/239 [==============================] - 108s 452ms/step - loss: 3.8509 - accuracy: 0.7884 - val_loss: 14.9132 - val_accuracy: 0.5396
Epoch 5/25
239/239 [==============================] - 106s 445ms/step - loss: 3.2218 - accuracy: 0.8157 - val_loss: 14.6992 - val_accuracy: 0.5623
Epoch 6/25
239/239 [==============================] - 108s 452ms/step - loss: 3.3474 - accuracy: 0.8147 - val_loss: 15.2357 - val_accuracy: 0.5547
Epoch 7/25
 57/239 [======>.......................] - ETA: 1:21 - loss: 2.9910 - accuracy: 0.8372

In [23]:
from tensorflow.keras.models import load_model
model.save('card_pred.h5')

In [16]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
model=load_model('card_pred.h5')

In [17]:
img=image.load_img('/content/drive/MyDrive/card dataset/dataset/valid/ace of clubs/1.jpg',target_size=(224,224))

In [18]:
x=image.img_to_array(img)
x

array([[[242., 238., 226.],
        [242., 238., 226.],
        [242., 238., 226.],
        ...,
        [242., 238., 226.],
        [242., 238., 226.],
        [242., 238., 226.]],

       [[242., 238., 226.],
        [242., 238., 226.],
        [242., 238., 226.],
        ...,
        [242., 238., 226.],
        [242., 238., 226.],
        [242., 238., 226.]],

       [[242., 238., 226.],
        [242., 238., 226.],
        [242., 238., 226.],
        ...,
        [242., 238., 226.],
        [242., 238., 226.],
        [242., 238., 226.]],

       ...,

       [[242., 238., 226.],
        [242., 238., 226.],
        [242., 238., 226.],
        ...,
        [242., 238., 226.],
        [242., 238., 226.],
        [242., 238., 226.]],

       [[242., 238., 226.],
        [242., 238., 226.],
        [242., 238., 226.],
        ...,
        [242., 238., 226.],
        [242., 238., 226.],
        [242., 238., 226.]],

       [[242., 238., 226.],
        [242., 238., 226.],
        [242., 2

In [19]:
x.shape

(224, 224, 3)

In [20]:
x=x/255
x=np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
img_data.shape

(1, 224, 224, 3)

In [21]:
model.predict(img_data)

1/1 [==============================] - 2s 2s/step


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.]], dtype=float32)

In [22]:
a=np.argmax(model.predict(img_data), axis=1)
a

1/1 [==============================] - 0s 25ms/step


array([24])